coaches/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^(?P<pk>\d+)/$', views.detail, name='detail'),
]

pybursa/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from . import views
from feedbacks.views import FeedbackView


urlpatterns = [
    # url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', admin.site.urls),

    url(r'^$', views.index, name = 'index'),
    url(r'^contact/$', views.contact, name = 'contact'),
    # url(r'^student_list/$', views.student_list, name = 'student_list'),
    # url(r'^student_detail/$', views.student_detail, name = 'student_detail'),

    url(r'^quadratic/', include('quadratic.urls')),

    url(r'^courses/', include('courses.urls', namespace="courses")),
    url(r'^students/', include('students.urls', namespace="students")),
    url(r'^coaches/', include('coaches.urls', namespace="coaches")),

    url(r'^feedback/$', FeedbackView.as_view(), name="feedback"),
]

students/urls.py
from django.conf.urls import url

from . import views

app_name = 'students'

urlpatterns = [
    url(r'^$', views.StudentListView.as_view(), name='list_view'),
    url(r'^(?P<pk>\d+)/$', views.StudentDetailView.as_view(), name='detail'),
    url(r'^add/$', views.StudentCreateView.as_view(), name='add'),
    url(r'^edit/(?P<pk>\d+)/$', views.StudentUpdateView.as_view(), name='edit'),
    url(r'^remove/(?P<pk>\d+)/$', views.StudentDeleteView.as_view(), name='remove'),
]

students/models.py
from django.db import models
from courses.models import Course


class Student(models.Model):
    name = models.CharField(max_length=255)
    surname = models.CharField(max_length=255)
    date_of_birth = models.DateField()
    email = models.EmailField()
    phone = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    skype = models.CharField(max_length=255)
    courses = models.ManyToManyField(Course)

    def __str__(self):
        return u'{} {}'.format(self.name, self.surname)

students/forms.py
from django import forms
from .models import Student


class StudentModelForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = "__all__"  # to avoid ImproperlyConfigured error

students/views.py
# -*- coding: utf-8 -*-

from django.contrib import messages
from django.core.urlresolvers import reverse_lazy
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView

import logging

from .models import Student
from .forms import StudentModelForm

logger = logging.getLogger(__name__)


class StudentListView(ListView):
    model = Student
    fields = '__all__'  # to avoid ImproperlyConfigured error
    paginate_by = 2

    def get_queryset(self):
        qs = super(StudentListView, self).get_queryset()
        course_id = self.request.GET.get('course_id', None)
        if course_id:
            qs = qs.filter(courses__id=course_id)
        return qs


class StudentDetailView(DetailView):

    model = Student
    fields = '__all__'  # to avoid ImproperlyConfigured error

    def get_context_data(self, **kwargs):

        context = super(StudentDetailView, self).get_context_data(**kwargs)

        logger.debug('Students detail view has been debugged')
        logger.info('Logger of students detail view informs you!')
        logger.warning('Logger of students detail view warns you!')
        logger.error('Students detail view went wrong!')

        return context


class StudentCreateView(CreateView):
    model = Student
    fields = '__all__'  # to avoid ImproperlyConfigured error
    # form_class = StudentModelForm
    # form = StudentModelForm  # to avoid ImproperlyConfigured error
    success_url = reverse_lazy('students:list_view')

    def get_context_data(self, **kwargs):
        context = super(StudentCreateView, self).get_context_data(**kwargs)
        context['title'] = "Student registration"
        return context

    def form_valid(self, form):
        data = form.cleaned_data
        messages.success(self.request, 'Student %s %s has been successfully added.' % (data['name'], data['surname']))
        return super(StudentCreateView, self).form_valid(form)

    # def form_valid(self, form):
    #     super_valid = super(StudentCreateView, self).form_valid(form)
    #     messages.success(self.request,
    #                      'Student {} {} has been successfully added.'.format(self.object.name, self.object.surname))
    #     return super_valid
    #
    # def get_context_data(self, **kwargs):
    #     context = super(StudentCreateView, self).get_context_data(**kwargs)
    #     context.update({
    #         "title": 'New student'
    #     })
    #     return context


class StudentUpdateView(UpdateView):
    model = Student
    fields = '__all__'  # to avoid ImproperlyConfigured error
    # form_class = StudentModelForm
    # form = StudentModelForm  # to avoid ImproperlyConfigured error
    success_url = reverse_lazy('students:list_view')
    # success_url = '/students/edit/%(id)d/'

    def get_context_data(self, **kwargs):
        context = super(StudentUpdateView, self).get_context_data(**kwargs)
        context['title'] = "Student info update"
        return context

    def form_valid(self, form):
        messages.success(self.request, 'Info on the student has been successfully changed.')
        return super(StudentUpdateView, self).form_valid(form)

    # def form_valid(self, form):
    #     messages.success(self.request, 'Info on the student has been successfully changed.')
    #     return super(StudentUpdateView, self).form_valid(form)
    #
    # def get_context_data(self, **kwargs):
    #     context = super(StudentUpdateView, self).get_context_data(**kwargs)
    #     context.update({
    #         "title": 'Edit student data'
    #     })
    #     return context


class StudentDeleteView(DeleteView):
    model = Student
    fields = '__all__'  # to avoid ImproperlyConfigured error
    # form_class = StudentModelForm
    # form = StudentModelForm  # to avoid ImproperlyConfigured error
    success_url = reverse_lazy('students:list_view')

    def get_context_data(self, **kwargs):
        context = super(StudentDeleteView, self).get_context_data(**kwargs)
        context['title'] = "Student info suppression"
        return context

    def delete(self, request, *args, **kwargs):
        student = self.get_object()
        messages.success(self.request, 'Info on %s %s has been successfully deleted.' % (student.name, student.surname))
        return super(StudentDeleteView, self).delete(request, *args, **kwargs)

    # def delete(self, request, *args, **kwargs):
    #     delete_super = super(StudentDeleteView, self).delete(request, *args, **kwargs)
    #     messages.success(self.request,
    #                      'Info on {} {} has been successfully deleted.'.
    #                      format(self.object.name, self.object.surname))
    #     return delete_super

templates/students/add.html
{% extends "base.html" %}


{% block title %}Создание студента - pyBursa{% endblock %}


{% block nav_students %}active{% endblock %}


{% block content %}
<div class="page-header">
  <h2>Создание нового студента</h2>
</div>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Создать">
  </form>
{% endblock content %}

templates/students/detail.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}Сведения о студенте - pyBursa{% endblock %}


{% block nav_students %}active{% endblock %}


{% block content %}
<div class="page-header">
  <h2>{{ student.name }} {{ student.surname }}</h2>
</div>

<div class="row">
  <div class="col-xs-12 col-lg-12">
    <div class="row">
      <div class="col-xs-4 col-lg-4 ">
        <table class="table">
          <thead>
            <tr>
              <td>дата рождения</td>
              <td>{{ student.date_of_birth|date:"d F, Y" }}</td>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>адрес</td>
              <td>{{ student.address }}</td>
            </tr>
            <tr>
              <td>почта</td>
              <td>{{ student.email }}</td>
            </tr>
            <tr>
              <td>логин skype</td>
              <td>{{ student.skype }}</td>
            </tr>
            <tr>
              <td>телефон</td>
              <td>{{ student.phone }}</td>
            </tr>
            <tr>
              <td>курсы</td>
              <td>
                {% for course in student.courses.all %}
                  <p><a href="{% url 'courses:detail' course.id %}">{{ course.name }}</a></p>
                {% endfor %}
              </td>
            </tr>
            <tr>
              <td>комментарии</td>
              <td>
                {{ comment|default:"не имеет комментарий" }}
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

templates/students/list.html
{% extends "base.html" %}


{% block title %}Студенты - pyBursa{% endblock %}


{% block nav_students %}active{% endblock %}


{% block content %}

{% if messages %}
  {% for message in messages %}
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      {{ message }}
    </div>
  {% endfor %}
{% endif %}

<a href="{% url 'students:add' %}" class="btn btn-primary" role="button">
  <span class="glyphicon glyphicon-plus"></span>
  Добавить нового студента
</a>
<div class="page-header">
  <h2>Список студентов</h2>
</div>
<div class="row">
  <div class="col-md-12">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>#</th>
          <th>фамилия имя</th>
          <th>адрес</th>
          <th>skype</th>
          <th>курсы</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for student in students %}
          <tr>
            <td>{{ forloop.counter }}</td>
            <td><a href="{% url 'students:detail' student.id %}">{{ student.surname }} {{ student.name }}</a></td>
            <td>{{ student.address }}</td>
            <td>{{ student.skype }}</td>
            <td>
              {% for course in student.courses.all %}
                <p><a href="{% url 'courses:detail' course.id %}">{{ course.name }}</a></p>
              {% endfor %}
            </td>
            <td>
              <a href="{% url 'students:edit' student.pk  %}" class="btn btn-primary" role="button">
                <span class="glyphicon glyphicon-pencil"></span>
                Изменить
              </a>
            </td>
            <td>
              <a href="{% url 'students:remove' student.pk  %}" class="btn btn-primary" role="button">
                <span class="glyphicon glyphicon-remove"></span>
                Удалить
              </a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock content %}

templates/students/remove.html
{% extends "base.html" %}


{% block title %}Удаление студента - pyBursa{% endblock %}


{% block nav_students %}active{% endblock %}


{% block content %}
<div class="page-header">
  <h4>Студент {{ student.name }} {{ student.surname }} будет удален</h4>
</div>
  <form method="post">
    {% csrf_token %}
    <input type="submit" value="Удалить">
  </form>
{% endblock content %}

templates/students/student_confirm_delete.html
{% extends "base.html" %}


{% block title %}Удаление студента - pyBursa{% endblock %}


{% block nav_students %}active{% endblock %}


{% block content %}
<div class="page-header">
  <h2>{{ title }}</h2>
  <!--<h4>Студент {{ student.name }} {{ student.surname }} будет удален</h4>-->
</div>
  <form method="post">
    {% csrf_token %}
    <input type="submit" value="Удалить">
  </form>
{% endblock content %}

templates/students/student_detail.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}Сведения о студенте - pyBursa{% endblock %}


{% block nav_students %}active{% endblock %}


{% block content %}
<div class="page-header">
  <h2>{{ student.name }} {{ student.surname }}</h2>
</div>

<div class="row">
  <div class="col-xs-12 col-lg-12">
    <div class="row">
      <div class="col-xs-4 col-lg-4 ">
        <table class="table">
          <thead>
            <tr>
              <td>дата рождения</td>
              <td>{{ student.date_of_birth|date:"d F, Y" }}</td>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>адрес</td>
              <td>{{ student.address }}</td>
            </tr>
            <tr>
              <td>почта</td>
              <td>{{ student.email }}</td>
            </tr>
            <tr>
              <td>логин skype</td>
              <td>{{ student.skype }}</td>
            </tr>
            <tr>
              <td>телефон</td>
              <td>{{ student.phone }}</td>
            </tr>
            <tr>
              <td>курсы</td>
              <td>
                {% for course in student.courses.all %}
                  <p><a href="{% url 'courses:detail' course.pk %}">{{ course.name }}</a></p>
                {% endfor %}
              </td>
            </tr>
            <tr>
              <td>комментарии</td>
              <td>
                {{ comment|default:"не имеет комментарий" }}
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

templates/students/student_form.html
{% extends "base.html" %}


{% block title %}{{ title }} - pyBursa{% endblock %}


{% block nav_students %}active{% endblock %}


{% block content %}

{% if messages %}
  {% for message in messages %}
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      {{ message }}
    </div>
  {% endfor %}
{% endif %}

<div class="page-header">
  <h2>{{ title }}</h2>
</div>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Сохранить">
  </form>
{% endblock content %}

templates/students/student_list.html
{% extends "base.html" %}


{% block title %}Студенты - pyBursa{% endblock %}


{% block nav_students %}active{% endblock %}


{% block content %}

{% if messages %}
  {% for message in messages %}
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      {{ message }}
    </div>
  {% endfor %}
{% endif %}

<a href="{% url 'students:add' %}" class="btn btn-primary" role="button">
  <span class="glyphicon glyphicon-plus"></span>
  Добавить нового студента
</a>
<div class="page-header">
  <h2>Список студентов</h2>
</div>
<div class="row">
  <div class="col-md-12">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>#</th>
          <th>фамилия имя</th>
          <th>адрес</th>
          <th>skype</th>
          <th>курсы</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for student in student_list %}
          <tr>
            <td>{{ forloop.counter }}</td>
            <td><a href="{% url 'students:detail' student.pk %}">{{ student.surname }} {{ student.name }}</a></td>
            <td>{{ student.address }}</td>
            <td>{{ student.skype }}</td>
            <td>
              {% for course in student.courses.all %}
                <p><a href="{% url 'courses:detail' course.pk %}">{{ course.name }}</a></p>
              {% endfor %}
            </td>
            <td>
              <a href="{% url 'students:edit' student.pk  %}" class="btn btn-primary" role="button">
                <span class="glyphicon glyphicon-pencil"></span>
                Изменить
              </a>
            </td>
            <td>
              <a href="{% url 'students:remove' student.id  %}" class="btn btn-primary" role="button">
                <span class="glyphicon glyphicon-remove"></span>
                Удалить
              </a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>

      <nav>
        <ul class="pagination">
          <li>
            {% if page_obj.has_previous %}
              <a href="?page={{ page_obj.previous_page_number }}" aria-label="<< previous">
                  <span aria-hidden="true">&laquo;</span>
                  previous
              </a>
            {% endif %}
          </li>
          {% for page in paginator.page_range %}

            {% if page_obj.number == page %}
              <li class="active">
                <a href="#" class="disabled">{{ page }}</a>
              </li>
            {% else %}
              <li>
                <a href="?page={{ page }}" class="disabled">{{ page }}</a>
              </li>
            {% endif %}

          {% endfor %}
          {% if page_obj.has_next %}
          <li>
            <a href="?page={{ page_obj.next_page_number }}" aria-label="next >>">
              <span aria-hidden="true">&raquo;</span>
              next
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>

  </div>
</div>
{% endblock content %}