coaches/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^(?P<pk>\d+)/$', views.detail, name='detail'),
]

pybursa/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from . import views
from feedbacks.views import FeedbackView


urlpatterns = [
    # url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', admin.site.urls),

    url(r'^$', views.index, name = 'index'),
    url(r'^contact/$', views.contact, name = 'contact'),
    # url(r'^student_list/$', views.student_list, name = 'student_list'),
    # url(r'^student_detail/$', views.student_detail, name = 'student_detail'),

    url(r'^quadratic/', include('quadratic.urls')),

    url(r'^courses/', include('courses.urls', namespace="courses")),
    url(r'^students/', include('students.urls', namespace="students")),
    url(r'^coaches/', include('coaches.urls', namespace="coaches")),

    url(r'^feedback/$', FeedbackView.as_view(), name="feedback"),
]

coaches/models.py
from django.contrib.auth.models import User
from django.db import models


class Coach(models.Model):

    GENDER_CHOICES = (
        (u'M', u'Male'),
        (u'F', u'Female'),
    )

    user = models.OneToOneField(User)
    date_of_birth = models.DateField()
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    phone = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    skype = models.CharField(max_length=255)
    description = models.TextField()

    def __str__(self):
        return self.user.username

coaches/views.py
from django.shortcuts import render, get_object_or_404
from .models import Coach


def detail(request, pk):
    coach = get_object_or_404(Coach, pk=pk)
    return render(request, 'coaches/detail.html', {'coach': coach})

templates/include/coach.html
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">{{ title }}</h3>
  </div>
  <div class="panel-body">
    <p><a href="{% url 'coaches:detail' coach.id %}">{{ coach.user.first_name }} {{ coach.user.last_name }}</a></p>
    <p>{{ coach.description }}</p>
  </div>
</div>

templates/include/coach_include.html
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">{{ title }}</h3>
  </div>
  <div class="panel-body">
    <p><a href="{% url 'coaches:detail' coach.id %}">{{ coach.user.first_name }} {{ coach.user.last_name }}</a></p>
    <p>{{ coach.description }}</p>
  </div>
</div>