coaches/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^(?P<pk>\d+)/$', views.detail, name='detail'),
]

courses/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^(?P<pk>\d+)/$', views.CourseDetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/add_lesson$', views.add_lesson, name='add-lesson'),
    url(r'^add/$', views.CourseCreateView.as_view(), name='add'),
    url(r'^edit/(?P<pk>\d+)/$', views.CourseUpdateView.as_view(), name='edit'),
    url(r'^remove/(?P<pk>\d+)/$', views.CourseDeleteView.as_view(), name='remove'),
]

pybursa/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from . import views
from feedbacks.views import FeedbackView


urlpatterns = [
    # url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', admin.site.urls),

    url(r'^$', views.index, name = 'index'),
    url(r'^contact/$', views.contact, name = 'contact'),
    # url(r'^student_list/$', views.student_list, name = 'student_list'),
    # url(r'^student_detail/$', views.student_detail, name = 'student_detail'),

    url(r'^quadratic/', include('quadratic.urls')),

    url(r'^courses/', include('courses.urls', namespace="courses")),
    url(r'^students/', include('students.urls', namespace="students")),
    url(r'^coaches/', include('coaches.urls', namespace="coaches")),

    url(r'^feedback/$', FeedbackView.as_view(), name="feedback"),
]

students/urls.py
from django.conf.urls import url

from . import views

app_name = 'students'

urlpatterns = [
    url(r'^$', views.StudentListView.as_view(), name='list_view'),
    url(r'^(?P<pk>\d+)/$', views.StudentDetailView.as_view(), name='detail'),
    url(r'^add/$', views.StudentCreateView.as_view(), name='add'),
    url(r'^edit/(?P<pk>\d+)/$', views.StudentUpdateView.as_view(), name='edit'),
    url(r'^remove/(?P<pk>\d+)/$', views.StudentDeleteView.as_view(), name='remove'),
]

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="{% static 'bootstrap/css/bootstrap-theme.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/theme.css' %}" rel="stylesheet">
  </head>

  <body role="document">

    <!-- Fixed navbar -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'index' %}">
            <img class="logo" src="{% static 'img/logo.png' %}" />
          </a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="{% block nav_index %}{% endblock %}">
              <a href="{% url 'index' %}">Главная</a>
            </li>
            <li class="{% block nav_contact %}{% endblock %}">
              <a href="{% url 'contact' %}">Контакты</a>
            </li>
            <li class="{% block nav_students %}{% endblock %}">
              <a href="{% url 'students:list_view' %}{% block students_course %}{% endblock %}">Студенты</a>
            </li>
            <li class="{% block nav_feedback %}{% endblock %}">
              <a href="{% url 'feedback' %}">Обратная связь</a>
            </li>
          </ul>
        </div><!--/.nav-collapse -->

      </div>
    </nav>

    <div class="container theme-showcase" role="main">

      {% block content %}{% endblock content %}

    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
  </body>
</html>

templates/contact.html
{% extends "base.html" %}

{% load staticfiles %}


{% block title %}Контакты - pyBursa{% endblock %}


{% block nav_contact %}active{% endblock %}


{% block content %}
<div class="jumbotron">
  <h1>Организаторы</h1>

  <div class="row">
    <div class="col-xs-6 col-lg-6">
      <h3>Основатель pyBursa</h3>
      <div class="row">
        <div class="col-xs-4 col-lg-4">
          <img src="{% static 'img/python.jpg' %}" />
        </div>
        <div class="col-xs-6 col-lg-6 ">
          <p>pyBursa@gmail.com</p>
          <p>skype: pyBursa</p>
          <p>+38 097 123 3 457</p>
        </div>
      </div>
    </div><!--/.col-xs-6.col-lg-6-->

    <div class="col-xs-6 col-lg-6">
      <h3>Менеджер pyBursa</h3>
      <div class="row">
        <div class="col-xs-4 col-lg-4">
          <img src="{% static 'img/python.jpg' %}" />
        </div>
        <div class="col-xs-6 col-lg-6 ">
          <p>pyBursa@gmail.com</p>
          <p>skype: pyBursa</p>
          <p>+38 097 123 3 457</p>
        </div>
      </div>
    </div><!--/.col-xs-6.col-lg-4-->

    <div class="col-xs-6 col-lg-6">
      <h3>Менеджер pyBursa</h3>
      <div class="row">
        <div class="col-xs-4 col-lg-4">
          <img src="{% static 'img/python.jpg' %}" />
        </div>
        <div class="col-xs-6 col-lg-6 ">
          <p>pyBursa@gmail.com</p>
          <p>skype: pyBursa</p>
          <p>+38 097 123 3 457</p>
        </div>
      </div>
    </div><!--/.col-xs-6.col-lg-4-->
  </div><!--/row-->
</div>
{% endblock content %}

templates/index.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}Pybursa Main{% endblock %}

{% block selected_main %}selected{% endblock %}

{% block content %}
	    <div class=main-header>
		<!--<img style="z-index:1" src={% static 'images/index.jpg'%}/>-->
		{% if messages %}
		<div class="alert alert-success alert-dismissible glow_cyan" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    		{% for message in messages %}
    		    {{ message }}
    		{% endfor %}
		</div>
		{% endif %}
		<h1 class="org_name">Jedi Academy</h1>
		<a href=#>Enroll for the course</a>
		<h1 class="org_name force">May the <b>Force</b> be with you</h1>
	    </div>
	    <div class=container>
	    	<h1 class="glow_cyan_t">Jedi Academy Courses, choose the side</h1>
		<p class="add_button"><a href="{% url 'courses:add' %}" class="glow_cyan">Add a new course</a></p>
	    	<table class="stud_table glow_cyan no_margin">
		    <thead>
		       <tr>
		    	    <th>Course</th>
		    	    <th>Description</th>
		    	    <th></th><th></th>
		       </tr>
		    </thead>
		    <tbody>
		    {% for course in courses %}
		       <tr>
		    	    <td><a href="{% url 'courses:detail' course.pk %}">{{ course|upper }}</a></td>
			    <td>{{ course.short_description|title }}</td>

			    <td class="table_center"><a href="{% url 'courses:edit' course.pk %}" class="btn btn-info">
					<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Edit</a></td>

			    <td class="table_center"><a href="{% url 'courses:remove' course.pk %}" class="btn btn-info">
					<span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Delete</a></td>
		       <tr>
		    {% endfor %}
		    </tbody>
	        </table>
	    </div>
{% endblock content %}

{% block footer %}footer{% endblock %}