coaches/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^(?P<pk>\d+)/$', views.detail, name='detail'),
]

courses/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^(?P<pk>\d+)/$', views.CourseDetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/add_lesson$', views.add_lesson, name='add-lesson'),
    url(r'^add/$', views.CourseCreateView.as_view(), name='add'),
    url(r'^edit/(?P<pk>\d+)/$', views.CourseUpdateView.as_view(), name='edit'),
    url(r'^remove/(?P<pk>\d+)/$', views.CourseDeleteView.as_view(), name='remove'),
]

pybursa/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from . import views
from feedbacks.views import FeedbackView


urlpatterns = [
    # url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', admin.site.urls),

    url(r'^$', views.index, name = 'index'),
    url(r'^contact/$', views.contact, name = 'contact'),
    # url(r'^student_list/$', views.student_list, name = 'student_list'),
    # url(r'^student_detail/$', views.student_detail, name = 'student_detail'),

    url(r'^quadratic/', include('quadratic.urls')),

    url(r'^courses/', include('courses.urls', namespace="courses")),
    url(r'^students/', include('students.urls', namespace="students")),
    url(r'^coaches/', include('coaches.urls', namespace="coaches")),

    url(r'^feedback/$', FeedbackView.as_view(), name="feedback"),
]

courses/models.py
from django.db import models
from coaches.models import Coach


class Course(models.Model):
    name = models.CharField(max_length=255)
    short_description = models.CharField(max_length=255)
    description = models.TextField()
    coach = models.ForeignKey(Coach, blank=True, null=True, related_name='coach_courses')
    assistant = models.ForeignKey(Coach, blank=True, null=True, related_name='assistant_courses')

    def __str__(self):
        return self.name


class Lesson(models.Model):
    subject = models.CharField(max_length=255)
    description = models.TextField()
    course = models.ForeignKey(Course)
    order = models.PositiveIntegerField()

    def __str__(self):
        return self.subject

    class Meta:
        ordering = ['order']

courses/forms.py
from django import forms
from .models import Course, Lesson


class CourseModelForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = '__all__'


class LessonModelForm(forms.ModelForm):
    class Meta:
        model = Lesson
        fields = '__all__'

courses/views.py
# -*- coding: utf-8 -*-

from django.contrib import messages
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView

import logging

from .forms import LessonModelForm, CourseModelForm
from .models import Course, Lesson

logger = logging.getLogger(__name__)


class CourseDetailView(DetailView):
    model = Course
    fields = '__all__'
    template_name = 'courses/detail.html'
    context_object_name = 'course'

    def get_context_data(self, **kwargs):

        logger.debug('Courses detail view has been debugged!')
        logger.info('Logger of courses detail view informs you!')
        logger.warning('Logger of courses detail view warns you!')
        logger.error('Courses detail view went wrong!')

        context = super(CourseDetailView, self).get_context_data(**kwargs)
        context['lessons'] = Lesson.objects.filter(course=self.get_object().pk)
        return context


class CourseCreateView(CreateView):
    model = Course
    fields = '__all__'  # to avoid ImproperlyConfigured error
    # form_class = CourseModelForm
    # form = CourseModelForm
    template_name = 'courses/add.html'
    context_object_name = 'form'
    success_url = reverse_lazy('index')

    def get_context_data(self, **kwargs):
        context = super(CourseCreateView, self).get_context_data(**kwargs)
        context['title'] = "Course creation"
        return context

    def form_valid(self, form):
        data = form.cleaned_data
        messages.success(self.request, 'Course %s has been successfully added.' % (data['name']))
        return super(CourseCreateView, self).form_valid(form)

    # def form_valid(self, form):
    #     super_valid = super(CourseCreateView, self).form_valid(form)
    #     messages.success(self.request,
    #                      'Course {} has been successfully added.'.format(self.object.name))
    #     return super_valid


class CourseUpdateView(UpdateView):
    model = Course
    fields = '__all__'  # to avoid ImproperlyConfigured error
    template_name = 'courses/edit.html'
    context_object_name = 'form'
    # success_url = reverse_lazy('index')
    # success_url = '/courses/edit/%(id)d/'

    def get_context_data(self, **kwargs):
        context = super(CourseUpdateView, self).get_context_data(**kwargs)
        context['title'] = "Course update"
        return context

    def form_valid(self, form):
        data = form.instance
        messages.success(self.request, 'The changes have been saved.')
        self.success_url = reverse_lazy('courses:edit', args=(data.id,))
        return super(CourseUpdateView, self).form_valid(form)

    # def form_valid(self, form):
    #     messages.success(self.request, 'The changes have been saved.')
    #     return super(CourseUpdateView, self).form_valid(form)


class CourseDeleteView(DeleteView):
    model = Course
    fields = '__all__'  # to avoid ImproperlyConfigured error
    template_name = 'courses/remove.html'
    context_object_name = 'form'
    success_url = reverse_lazy('index')

    def get_context_data(self, **kwargs):
        context = super(CourseDeleteView, self).get_context_data(**kwargs)
        context['title'] = "Course deletion"
        return context

    def delete(self, request, *args, **kwargs):
        course = self.get_object()
        messages.success(self.request, 'Course %s has been deleted.' % (course.name))
        return super(CourseDeleteView, self).delete(request, *args, **kwargs)

    # def delete(self, request, *args, **kwargs):
    #     delete_super = super(CourseDeleteView, self).delete(request, *args, **kwargs)
    #     messages.success(self.request,
    #                      'Course {} has been deleted.'.format(self.object.name))
    #     return delete_super


def add_lesson(request, pk):
    course = get_object_or_404(Course, pk=pk)
    if request.method == "POST":
        form = LessonModelForm(request.POST)
        if form.is_valid():
            lesson = form.save()
            messages.success(request, 'Lesson {} has been successfully added.'.format(lesson.subject))
            return redirect('courses:detail', lesson.course_id)
    else:
        form = LessonModelForm(initial={'course': course})
    return render(request, 'courses/add_lesson.html', {'form': form})

templates/courses/add.html
{% extends "base.html" %}

{% block title %}{{ title }}{% endblock %}

{% block selected_main %}selected{% endblock %}

{% block content %}
        <div class="container at_center">
	<h1 class="glow_cyan_t">{{ title }}</h1>
		<form method="post">
			{% csrf_token %}
			<table>
			{{ form.as_table }}
			</table>
			<input type="submit" value="Create" />
		</form>
    	</div>
{% endblock content %}

{% block footer %}"footer atbottom"{% endblock %}

templates/courses/add_lesson.html
{% extends "base.html" %}


{% block title %}Создание занятия - pyBursa{% endblock %}


{% block content %}
<div class="page-header">
  <h2>{{ title }}</h2>
</div>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Создать">
  </form>
{% endblock content %}

templates/courses/detail.html
{% extends "base.html" %}


{% block title %}Сведенья о курсе - pyBursa{% endblock %}

{% block students_course %}?course_id={{ course.pk }}{% endblock %}


{% block content %}
{% if messages %}
  {% for message in messages %}
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      {{ message }}
    </div>
  {% endfor %}
{% endif %}

<div class="jumbotron">
  <h1>{{ course.name }}</h1>
  <p>{{ course.description }}</p>
</div>

<div class="page-header">
  <h1>Преподаватели</h1>
</div>
  {% if course.coach %}
    {% include "include/coach_include.html" with title="Учитель" coach=course.coach %}
  {% endif %}

  {% if course.assistant %}
    {% include "include/coach_include.html" with title="Ассистент" coach=course.assistant %}
  {% endif %}

<div class="page-header">
  <h1>План курса</h1>
</div>

<a href="{% url 'courses:add-lesson' course.pk %}" class="btn btn-primary" role="button">
  <span class="glyphicon glyphicon-plus"></span>
  Добавить занятие
</a>

<div class="row">
  <div class="col-md-12">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>#</th>
          <th>Тема</th>
          <th>Описание</th>
        </tr>
      </thead>
      <tbody>
        {% for lesson in course.lesson_set.all %}
          <tr>
            <td>{{ lesson.order }}</td>
            <td>{{ lesson.subject }}</td>
            <td>{{ lesson.description }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock content %}

templates/courses/edit.html
{% extends "base.html" %}


{% block title %}Редактирование курса - pyBursa{% endblock %}


{% block content %}

{% if messages %}
  {% for message in messages %}
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      {{ message }}
    </div>
  {% endfor %}
{% endif %}

<div class="page-header">
  <h2>{{ title }}</h2>
</div>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Изменить">
  </form>
{% endblock content %}

templates/courses/remove.html
{% extends "base.html" %}


{% block title %}Удаление курса - pyBursa{% endblock %}


{% block content %}
<div class="page-header">
  <h2>{{ title }}</h2>
</div>
  <form method="post">
    {% csrf_token %}
    <input type="submit" value="Удалить">
  </form>
{% endblock content %}